name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag jobet:$(date +%s)
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Check Node.js version
      run: node -v

    - name: Install dependencies
      run: npm install
    
    - name: Run Prettier
      run: |
        npm install --save-dev prettier
        npx prettier --write "src/**/*.{js,jsx}"

    - name: Initiate ESLint config
      run: npm init @eslint/config --yes
      
    - name: Run ESLint
      run: |
        npm install --save-dev eslint-plugin-jsx-a11y
        npx eslint "src/**/*.{js,jsx}" --fix

    - name: Run build
      run: npm run build
    
    - name: Run tests
      run: npm run test
