name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag jobet:$(date +%s)

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: ESLint Code Lint & Fix
  # You may pin to the exact commit or the version.
  # uses: permafrost-dev/eslint-docker-ga@0611438792291217c8c826957841d6aba36cfb99
      uses: permafrost-dev/eslint-docker-ga@v1.0.0
          
    - name: Run ESLint and Prettier
      run: |
        npm run lint-fix
        npm run format-fix

    - name: Commit changes
      run: |
        git config --global.user.name 'github-actions[bot]'
        git config --global.user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Fix code style issues with ESLint and Prettier" || true
        git push origin

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test
